# Generated by Django 4.1.7 on 2023-03-29 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего редактирования')),
                ('model_name', models.CharField(max_length=255, verbose_name='Кодовое имя сущности')),
                ('model_verbose_name', models.CharField(max_length=255, verbose_name='Название сущности')),
                ('model_verbose_name_plural', models.CharField(max_length=255, verbose_name='Название сущности в множественном числе')),
                ('has_images', models.BooleanField(default=False, verbose_name='Наличие множества картинок')),
                ('is_instantiated', models.BooleanField(default=False, verbose_name='Инициализация')),
                ('multilingualism', models.BooleanField(default=False, verbose_name='Мультиязычность')),
                ('in_admin_panel', models.BooleanField(default=False, verbose_name='Наличие в админке')),
                ('has_API', models.BooleanField(default=False, verbose_name='Наличие API')),
            ],
            options={
                'verbose_name': 'Образ модели',
                'verbose_name_plural': 'Образы моделей',
            },
        ),
        migrations.CreateModel(
            name='TextFieldImage',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего редактирования')),
                ('field_name', models.CharField(max_length=255, verbose_name='Кодовое имя поля')),
                ('field_verbose_name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('is_required_field', models.BooleanField(default=False, verbose_name='Обязательное поле?')),
                ('is_translatable', models.BooleanField(default=True, verbose_name='Переводимое поле')),
                ('model_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage', verbose_name='Образ родительской модели')),
            ],
            options={
                'verbose_name': 'Образ текстового поля',
                'verbose_name_plural': 'Образы текстовых полей',
            },
        ),
        migrations.CreateModel(
            name='ImageFieldImage',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего редактирования')),
                ('field_name', models.CharField(max_length=255, verbose_name='Кодовое имя поля')),
                ('field_verbose_name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('is_required_field', models.BooleanField(default=False, verbose_name='Обязательное поле?')),
                ('model_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage', verbose_name='Образ родительской модели')),
            ],
            options={
                'verbose_name': 'Образ поля картинки',
                'verbose_name_plural': 'Образы полей картинок',
            },
        ),
        migrations.CreateModel(
            name='CharFieldImage',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего редактирования')),
                ('field_name', models.CharField(max_length=255, verbose_name='Кодовое имя поля')),
                ('field_verbose_name', models.CharField(max_length=255, verbose_name='Название поля')),
                ('is_required_field', models.BooleanField(default=False, verbose_name='Обязательное поле?')),
                ('is_translatable', models.BooleanField(default=True, verbose_name='Переводимое поле?')),
                ('in_list_display', models.BooleanField(default=False, verbose_name='List Display')),
                ('in_search_fields', models.BooleanField(default=False, verbose_name='Search Field')),
                ('model_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage', verbose_name='Образ родительской модели')),
            ],
            options={
                'verbose_name': 'Образ малого текстового поля',
                'verbose_name_plural': 'Образы малых текстовых полей',
            },
        ),
    ]
