# Generated by Django 4.1.7 on 2023-03-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charfieldimage',
            options={'verbose_name': 'CharField Image', 'verbose_name_plural': 'Images of CharFields'},
        ),
        migrations.AlterModelOptions(
            name='imagefieldimage',
            options={'verbose_name': 'ImageField Image', 'verbose_name_plural': 'Images of ImageFields'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name': 'Model Image', 'verbose_name_plural': 'Model Images'},
        ),
        migrations.AlterModelOptions(
            name='textfieldimage',
            options={'verbose_name': 'TextField Image', 'verbose_name_plural': 'Images of TextFields'},
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='multilingualism',
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='field_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='field_verbose_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='in_list_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='in_search_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='is_required_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='is_translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='model_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage'),
        ),
        migrations.AlterField(
            model_name='charfieldimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='field_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='field_verbose_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='is_required_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='model_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage'),
        ),
        migrations.AlterField(
            model_name='imagefieldimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='has_API',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='in_admin_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='is_instantiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='model_verbose_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='model_verbose_name_plural',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='field_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='field_verbose_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='is_required_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='is_translatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='model_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.modelimage'),
        ),
        migrations.AlterField(
            model_name='textfieldimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
