# Generated by Django 4.1.7 on 2023-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_charfieldimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelimage',
            name='multilingualism',
            field=models.BooleanField(default=False),
        ),
    ]
